services:
  backend:
    build: ./backend
    container_name: fahrtenbuch-backend
    ports:
      - "3000:3000"         # extern erreichbar (optional)
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: fahrtenbuch-frontend
    ports:
      - "8080:80"           # Frontend über Port 8080 erreichbar
    restart: unless-stopped
    depends_on:
      - backend
