name: Build Docker Images

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate image tag
        id: tag
        run: |
          DATE=$(date +"%Y.%m.%d")
          RAND=$(uuidgen | cut -d'-' -f1)
          echo "IMAGE_TAG=${DATE}-${RAND}" >> $GITHUB_ENV

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build \
            -t frontend:${IMAGE_TAG} \
            -f Dockerfile \
            frontend

      - name: Build Backend Docker Image
        run: |
          cd backend
          docker build \
            -t backend:${IMAGE_TAG} \
            -f  Dockerfile \
            backend