name: Build & Push Docker Images to GHCR

on:
  push:
    branches:
      - "**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate image tag
        id: tag
        run: |
          DATE=$(date +"%Y.%m.%d")
          RAND=$(uuidgen | cut -d'-' -f1)
          echo "image_tag=${DATE}-${RAND}" >> $GITHUB_OUTPUT

      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/fahrtenbuch-frontend:${{ needs.detect-changes.outputs.image_tag }} \
            -f frontend/Dockerfile \
            frontend

          docker push ghcr.io/${{ github.repository_owner }}/fahrtenbuch-frontend:${{ needs.detect-changes.outputs.image_tag }}

  backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/fahrtenbuch-backend:${{ needs.detect-changes.outputs.image_tag }} \
            -f backend/Dockerfile \
            backend

          docker push ghcr.io/${{ github.repository_owner }}/fahrtenbuch-backend:${{ needs.detect-changes.outputs.image_tag }}
